version: "3"

volumes:
  postgres_db_vol: {}
  redis_cache_vol: {}
  django_static_vol: {}
  vue_dist_vol: {}

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - django_static_vol:/data/static/
      - vue_dist_vol:/data/client/dist/
    ports:
      - "80:80"
    depends_on:
      - django

  certbot:
    container_name: certbot
    image: certbot/certbot:v0.36.0
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    expose:
      - 5432

  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - redis_cache_vol:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 3s
      timeout: 1s
      retries: 5
    expose:
      - 6379

  django:
    container_name: django
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    image: $BACK_IMAGE_NAME
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DJANGO_DEBUG=False
      - DOCKERIZED=1
    volumes:
      - django_static_vol:/home/server/.static_root/
    working_dir: /home/server/
    command: >
      bash -c "
      chmod +x /wait-for-it.sh
      && /wait-for-it.sh postgres:5432 -t 10
      && python manage.py migrate
      && echo yes | python manage.py collectstatic
      && gunicorn --bind 0:8000 server.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
  
