version: "3"

volumes:
  postgres_db_vol: {}
  redis_cache_vol: {}

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=movie-tender
      - POSTGRES_USER=movie-tender
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    expose:
      - 5432

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_cache_vol:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 3s
      timeout: 1s
      retries: 5
    ports:
      - 6379

  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=movie-tender
      - POSTGRES_USER=movie-tender
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - DOCKERIZED=1
    volumes:
      - ./:/app/
    working_dir: /app/
    command: >
      bash -c "
      chmod +x /wait-for-it.sh
      && /wait-for-it.sh postgres:5432 -t 10
      && python manage.py migrate
      && python manage.py runserver"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
  
