# Generated by Django 4.0.6 on 2022-07-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-id'], name='idx_review_iddesc'),
        ),
    ]
