# Generated by Django 3.2.12 on 2022-06-10 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='_genres',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='keywords',
            new_name='_keywords',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='providers',
            new_name='_providers',
        ),
        migrations.AlterField(
            model_name='movie',
            name='_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, db_column='genres', size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, db_column='keywords', size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='_providers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, db_column='providers', default=list, size=None),
        ),
    ]
