# Generated by Django 3.2.12 on 2022-06-11 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220610_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, db_column='genres', default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, db_column='keywords', default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='_providers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, db_column='providers', default=list, size=None),
        ),
    ]
