# Generated by Django 4.0.6 on 2022-08-20 18:33

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_credit_character'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_keyword_afd773_gin',
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id'], name='idx_movie_tmdb_id'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_keywords'], name='idx_keywords'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['tmdb_id'], name='idx_staff_tmdb_id'),
        ),
    ]
