name: Django CI

on: [push, pull_request]

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github-actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Create secrets
      run: echo "${{ secrets.DOTENV }}" > server/.env

    - name: Install dependencies
      run: |
        cd server/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage codecov

    - name: Run tests
      run: |
        cd server/
        python manage.py migrate
        coverage run ./manage.py test
        codecov