name: Vue CI

on:
  pull_request:
    branches:
      - master

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # - name: Cache dependency
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      # - name: Create secrets
      #   run: echo "${{ secrets.DOTENV }}" > client/.env

      # - name: Set up Python 3.9
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.9

      # - name: Install dependencies
      #   run: |
      #     cd client/
      #     npm install

      # - name: Run tests
      #   run: |
      #     cd client/

      - name: Dockerize
        run: |
          echo "${{ secrets.DOCKER_HUB_PW }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
          docker build -t "${{ secrets.FRONT_IMAGE_NAME }}" ./client/
          docker push "${{ secrets.FRONT_IMAGE_NAME }}"
          docker logout

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Run scripts
        run: |
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/SSH_KEY.key
          chmod 600 ~/.ssh/SSH_KEY.key
          ssh-add ~/.ssh/SSH_KEY.key
          ssh ubuntu@"${{ secrets.DEPLOY_SERVER_IP }}" sudo bash deploy.sh
