name: Vue CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # - name: Cache dependency
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/npm
      #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-npm-

      # - name: Create secrets
      #   run: echo "${{ secrets.FRONT_DOTENV }}" > client/.env

      # - name: Set up Node.js 16.16
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 16.16

      # - name: Install dependencies
      #   run: |
      #     cd client/
      #     npm install

      # - name: Run tests
      #   run: |
      #     cd client/
      #     npm run test

      - name: Dockerize
        run: |
          echo "${{ secrets.DOCKER_HUB_PW }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
          docker build -t "${{ secrets.FRONT_IMAGE_NAME }}" ./client/
          docker push "${{ secrets.FRONT_IMAGE_NAME }}"
          docker logout
